blood_codes = [{"val0": "A1A", "val1": "Alpha-1 Antitrypsin"},
               {"val0": "A1c", "val1": "Hemoglobin A1c"},
               {"val0": "AB", "val1": "Antibody"},
               {"val0": "ABG", "val1": "Arterial Blood Gas"},
               {"val0": "ABRH ", "val1": "ABO Group and Rh Type"},
               {"val0": "ABT", "val1": "Antibody Titer"},
               {"val0": "ACA", "val1": "Anti-Cardiolipin Antibodies"},
               {"val0": "ACE", "val1": "Angiotensin Converting Enzyme"},
               {"val0": "ACID PHOS ", "val1": "Acid Phosphatase"},
               {"val0": "ACP", "val1": "Acid Phosphatase"},
               {"val0": "ACT", "val1": "Activated Clotting Time"},
               {"val0": "ACTH", "val1": "Adrenocorticotropic Hormone"},
               {"val0": "ADA", "val1": "Adenosine Deaminase"},
               {"val0": "AFB", "val1": "Acid-Fast Bacillus"},
               {"val0": "AFP", "val1": "Alpha Fetoprotein"},
               {"val0": "AG", "val1": "Antigen"},
               {"val0": "ALA", "val1": "Aminolevulinic Acid"},
               {"val0": "Alb", "val1": "Albumin"},
               {"val0": "Alk Phos", "val1": "Alkaline Phosphatase"},
               {"val0": "ALP", "val1": "Alkaline Phosphatase"},
               {"val0": "ANA", "val1": "Antinuclear Antibody"},
               {"val0": "Anti-HBc", "val1": "Hepatitis B Core Antibody"},
               {"val0": "Anti-HBe", "val1": "Hepatitis Be Antibody"},
               {"val0": "Anti-HBs", "val1": "Hepatitis B Surface Antibody"},
               {"val0": "Anti-HCV", "val1": "Hepatitis C Antibody"},
               {"val0": "APT", "val1": "Stool for Fetal Hemoglobin"},
               {"val0": "aPTT", "val1": "Activated Partial Thrombin Time"},
               {"val0": "ASN", "val1": "Antibody Screen"},
               {"val0": "ASO", "val1": "Antistreptolysin-O"},
               {"val0": "ASP", "val1": "Aspirin Resistance"},
               {"val0": "AT III ", "val1": "Antithrombin-III Activity"},
               {"val0": "B12", "val1": "Vitamin B12"},
               {"val0": "BMP", "val1": "Basic Metabolic Panel"},
               {"val0": "BNP", "val1": "Brain Natriuretic Peptide"},
               {"val0": "BUN ", "val1": "Blood Urea Nitrogen"},
               {"val0": "C1", "val1": "Complement C1, Functional"},
               {"val0": "C1Q", "val1": "C1Q Binding Assay"},
               {"val0": "C2", "val1": "Complement C2"},
               {"val0": "C3", "val1": "Complement C3"},
               {"val0": "C4", "val1": " Complement C4"},
               {"val0": "Ca", "val1": "Calcium"},
               {"val0": "CBC", "val1": "Complete Blood Count"},
               {"val0": "CBCD", "val1": "Complete Blood Count with Differential"},
               {"val0": "CEA", "val1": "Carcinoembryonic Antigen"},
               {"val0": "CH50  ", "val1": "Complement Immunoassay, Total"},
               {"val0": "CK", "val1": "Creatine Kinase"},
               {"val0": "Cl ", "val1": "Chloride"},
               {"val0": "CMB", "val1": "CKMB Panel"},
               {"val0": "CMP", "val1": "Comprehensive Metabolic Panel"},
               {"val0": "CMV", "val1": "Cytomegalovirus"},
               {"val0": "CMV Ag", "val1": "CMV Antigenemia"},
               {"val0": "CO", "val1": "Carbon Monoxide"},
               {"val0": "CO2", "val1": "Carbon Dioxide"},
               {"val0": "COHB", "val1": "Carboxyhemoglobin"},
               {"val0": "CONABO", "val1": "Confirmatory Type"},
               {"val0": "CPK", "val1": "Creatine Phosphokinase (Creatine Kinase)"},
               {"val0": "Cr", "val1": "Creatinine"},
               {"val0": "CRCL, CrCl", "val1": "Creatinine Clearance"},
               {"val0": "CRD", "val1": "Cord Type and DAT"},
               {"val0": "CREAT", "val1": "Creatinine"},
               {"val0": "CRP", "val1": "C-Reactive Protein"},
               {"val0": "Cu", "val1": "Copper"},
               {"val0": "D Bil ", "val1": "Direct Bilirubin"},
               {"val0": "DAT", "val1": "Direct Antiglobulin (Coombs) Test"},
               {"val0": "DCAS", "val1": "DAT and AB Screen"},
               {"val0": "DHEA ", "val1": "Dehydroepiandrosterone"},
               {"val0": "DHEAS ", "val1": "Dehydroepiandrosterone-Sulfate"},
               {"val0": "DIFM", "val1": "Differential"},
               {"val0": "Dig", "val1": "Digoxin"},
               {"val0": "EOS", "val1": "Eosinophils"},
               {"val0": "EPO", "val1": "Erythropoietin"},
               {"val0": "ERA", "val1": "Estrogen Receptor Assay"},
               {"val0": "ESR", "val1": "Erythrocyte Sedimentation Rate"},
               {"val0": "ETOH", "val1": "Ethanol"},
               {"val0": "FBS", "val1": "Fasting Blood Sugar (Glucose)"},
               {"val0": "Fe", "val1": "Total Iron"},
               {"val0": "FEP", "val1": "Free Erythrocyte Protoporphyrin"},
               {"val0": "FFN", "val1": "Fetal Fibronectin"},
               {"val0": "FFQ", "val1": "Fecal Fat"},
               {"val0": "Fol", "val1": "Folate"},
               {"val0": "FSH/LH", "val1": "FSH/LH Evaluation"},
               {"val0": "FT3", "val1": "Free T3"},
               {"val0": "FT4", "val1": "Free Thyroxine"},
               {"val0": "G2PP", "val1": "2 Hour Postprandial Glucose"},
               {"val0": "G-6-PD", "val1": "Glucose-6-Phosphate Dehydrogenase"},
               {"val0": "Gamma GT ", "val1": "Gamma Glutamyl Transferase"},
               {"val0": "GCT", "val1": "Glucose Challenge Test"},
               {"val0": "GDS", "val1": "Gestational Diabetes Screen"},
               {"val0": "GGT", "val1": "Gamma Glutamyl Transferase"},
               {"val0": "GH", "val1": "Growth Hormone"},
               {"val0": "Glu", "val1": "Glucose"},
               {"val0": "H&H (or H/H)", "val1": "Hemoglobin and Hematocrit"},
               {"val0": "Hapto", "val1": "Haptoglobin"},
               {"val0": "HbA1c", "val1": "Hemoglobin A1c"},
               {"val0": "HBeAb", "val1": "Hepatitis Be Virus Antibody"},
               {"val0": "HBeAg", "val1": "Hepatitis Be Virus Antigen "},
               {"val0": "HBsAb", "val1": "Hepatitis B Surface Antibody"},
               {"val0": "HBsAg", "val1": "Hepatitis B Surface Antigen"},
               {"val0": "hCG", "val1": "Human Chorionic Gonadotropin"},
               {"val0": "hCG (urine)", "val1": "Urine Pregnancy Test"},
               {"val0": "HCT", "val1": "Hematocrit"},
               {"val0": "HDL", "val1": "High Density Lipoprotein"},
               {"val0": "HFP", "val1": "Hepatic Function Panel"},
               {"val0": "HGB", "val1": "Hemoglobin"},
               {"val0": "HgbA1c", "val1": "Hemoglobin A1c"},
               {"val0": "HGH", "val1": "Human Growth Hormone"},
               {"val0": "HIAA", "val1": "5-Hydroxyindoleacetic Acid"},
               {"val0": "HIV", "val1": "Human Immunodeficiency Virus"},
               {"val0": "HPV", "val1": "Human Papilloma Virus"},
               {"val0": "HSV", "val1": "Herpes Simplex Virus"},
               {"val0": "iCa", "val1": "Ionized Calcium"},
               {"val0": "IFE", "val1": "Immunofixation Electrophoresis"},
               {"val0": "IgA", "val1": "Immunoglobulin A"},
               {"val0": "IgE", "val1": "Immunoglobulin E"},
               {"val0": "IGF", "val1": "Insulin-Like Growth Factor-I"},
               {"val0": "IgG ", "val1": "Immunoglobulin G"},
               {"val0": "IgM ", "val1": "Immunoglobulin M"},
               {"val0": "INR", "val1": "Prothrombin Time"},
               {"val0": "Jo-1", "val1": "Jo-1 Antibody"},
               {"val0": "KB", "val1": "Kleihauer-Betke"},
               {"val0": "K", "val1": "Potassium"},
               {"val0": "Lact(o)", "val1": "Lactoferrin"},
               {"val0": "LD", "val1": "Lactate Dehydrogenase"},
               {"val0": "LDH", "val1": "Lactate Dehydrogenase"},
               {"val0": "LFT", "val1": "Liver Function Tests"},
               {"val0": "LH", "val1": "Luteinizing Hormone"},
               {"val0": "Li+ or Li", "val1": "Lithium"},
               {"val0": "MetHb/MetHgb ", "val1": "Methemoglobin"},
               {"val0": "Mg, Mag", "val1": "Magnesium"},
               {"val0": "MIC", "val1": "Minimum Inhibitory Concentration"},
               {"val0": "MMA", "val1": "Methylmalonic Acid"},
               {"val0": "Mn", "val1": "Manganese"},
               {"val0": "Mono", "val1": "Mononucleosis"},
               {"val0": "NA", "val1": "Sodium"},
               {"val0": "NEOTY", "val1": "Neonate Type and DAT"},
               {"val0": "NEOXM", "val1": "Neonate Type and XM  "},
               {"val0": "NH3", "val1": "Ammonia"},
               {"val0": "NTR", "val1": "Newborn Type and Rh"},
               {"val0": "PAP", "val1": "Pap Smear OR"},
               {"val0": " ", "val1": "Pap Smear & HPV DNA Test OR"},
               {"val0": " ", "val1": "Prostatic Acid Phosphatase"},
               {"val0": "Pb", "val1": "Lead"},
               {"val0": "PBG", "val1": "Porphobilinogen"},
               {"val0": "PCP", "val1": "Phencyclidine"},
               {"val0": "PEP", "val1": "Protein Electrophoresis"},
               {"val0": "PHOS", "val1": "Phosphorus"},
               {"val0": "PKU", "val1": "Phenylketonuria"},
               {"val0": "PLT or PLT Ct", "val1": "Platelet Count"},
               {"val0": "PO4", "val1": "Phosphorus"},
               {"val0": "PRL", "val1": "Prolactin"},
               {"val0": "PRU", "val1": "P2Y12"},
               {"val0": "PSA", "val1": "Prostate Specific Antigen"},
               {"val0": "PT ", "val1": "Prothrombin Time"},
               {"val0": "PTH", "val1": "Parathyroid Hormone"},
               {"val0": "PTT", "val1": "Partial Thromboplastin Time"},
               {"val0": "QIG", "val1": "Quantitative Immunoglobulins"},
               {"val0": "RBC", "val1": "Red Blood Cell"},
               {"val0": "RET", "val1": "Reticulocyte Count"},
               {"val0": "RF ", "val1": "Rheumatoid Factor"},
               {"val0": "RFP", "val1": "Renal Function Panel"},
               {"val0": "RhIG (Eval)", "val1": "RhIG Evaluation"},
               {"val0": "RPR", "val1": "Rapid Plasma Reagin"},
               {"val0": "RSV", "val1": "Respiratory Syncytial Virus"},
               {"val0": "Scl-70", "val1": "Scleroderma Antibody"},
               {"val0": "SHBG", "val1": "Sex Hormone-Binding Globulin"},
               {"val0": "SIFE", "val1": "Serum Immunofixation Electrophoresis"},
               {"val0": "Siro", "val1": "Sirolimus"},
               {"val0": "SPEP", "val1": "Serum Protein Electrophoresis"},
               {"val0": "SSA", "val1": "Sjögren’s Syndrome A Antibody"},
               {"val0": "SSB", "val1": "Sjögren’s Syndrome B Antibody"},
               {"val0": "SSDNA", "val1": "Single Stranded DNA"},
               {"val0": "T Bil", "val1": "Total Bilirubin"},
               {"val0": "T3", "val1": "Triiodothyronine"},
               {"val0": "T4", "val1": "Thyroxine"},
               {"val0": "Tacro", "val1": "Tacrolimus"},
               {"val0": "TBG", "val1": "Thyroxine Binding Globulin"},
               {"val0": "TGL", "val1": " Triglycerides"},
               {"val0": "Theo", "val1": "Theophylline"},
               {"val0": "TIBC", "val1": "Total Iron Binding Capacity"},
               {"val0": "TP", "val1": "Total Protein"},
               {"val0": "TREP", "val1": "Treponemal Antibodies"},
               {"val0": "Trep Ab", "val1": "Treponemal Antibodies"},
               {"val0": "TRH ", "val1": " Thyrotropin Releasing Hormone"},
               {"val0": "Trig", "val1": "Triglycerides"},
               {"val0": "TRXN", "val1": "Transfusion Reaction Evaluation"},
               {"val0": "TSH", "val1": "Thyroid Stimulating Hormone"},
               {"val0": "TSI", "val1": "Thyroid Stimulating Immunoglobulin"},
               {"val0": "TT", "val1": "Thrombin Time"},
               {"val0": "TYSC", "val1": "Type and Screen"},
               {"val0": "UIFE", "val1": "Urine Immunofixation Electrophoresis"},
               {"val0": "UPE, UPEP or", "val1": " "},
               {"val0": "Ur Prot Elect", "val1": "Urine Protein Electrophoresis"},
               {"val0": "VCA", "val1": "Viral Capsid Antigen "},
               {"val0": "VDRL", "val1": "Venereal Disease Reference Lab (Syphilis Test, CSF)"},
               {"val0": "Vit A", "val1": "Vitamin A (Retinol)"},
               {"val0": "Vit B1", "val1": "Vitamin B1 (Thiamine)"},
               {"val0": "Vit B12", "val1": "Vitamin B12"},
               {"val0": "Vit B2 ", "val1": "Vitamin B2 (Riboflavin)"},
               {"val0": "Vit B6", "val1": "Vitamin B6 (Pyridoxine)"},
               {"val0": "Vit C", "val1": "Vitamin C"},
               {"val0": "Vit D", "val1": "25-Hydroxy Vitamin D"},
               {"val0": "VLDL", "val1": "Very Low Density Lipoprotein"},
               {"val0": "VMA", "val1": "Vanillylmandelic Acid"},
               {"val0": "VZG", "val1": "Varicella zoster IgG"},
               {"val0": "WBC", "val1": "White Blood Cell Count"},
               {"val0": "Xa", "val1": "LMW Heparin"},
               {"val0": "XM", "val1": "Type and Crossmatch"},
               {"val0": "Zn", "val1": "Zinc"},
               {"val0": "ZPP", "val1": "Zinc Protoporphyrin"}];
